name: Build Paper

on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build PDF
        run: |
          cd paper/
          nix build
      - name: Upload as release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "paper/result/abs-den*.pdf"
          branches: main
          tag_name: "Latest"
          overwrite: true
          draft: false
      - name: Run tests
        run: |
          cd paper/
          nix develop --command bash -c "make test"
