name: Build Paper

on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build PDF
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make -C paper abs-den.pdf abs-den-ext.pdf
      - name: Upload as release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "paper/abs-den*.pdf"
          branches: main
          tag_name: "Latest"
          overwrite: true
