name: Build Paper

on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Cache lhs2TeX
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lhs2tex texlive-full ghc
          version: 1.1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build PDF
        run: make -C paper abs-den.pdf abs-den-ext.pdf
      - name: Upload as release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "paper/abs-den*.pdf"
          branches: main
          tag_name: "Latest"
          overwrite: true
      - name: Run tests
        run: make -C paper test
